export const GET_BOOKING = "GET_BOOKING";
export const GET_BOOKING_SUCCEED = "GET_BOOKING_SUCCEED";
export const GET_BOOKING_FAIL = "GET_BOOKING_FAIL";

export const BOOKING_CANCEL = "BOOKING_CANCEL";
export const BOOKING_CANCEL_SUCCEED = "BOOKING_CANCEL_SUCCEED";
export const BOOKING_CANCEL_FAIL = "BOOKING_CANCEL_FAIL";

export const BOOKING_APPROVE = "BOOKING_APPROVE";
export const BOOKING_APPROVE_SUCCEED = "BOOKING_APPROVE_SUCCEED";
export const BOOKING_APPROVE_FAIL = "BOOKING_APPROVE_FAIL";

export const BOOKING_CHECKIN = "BOOKING_CHECKIN";
export const BOOKING_CHECKIN_SUCCEED = "BOOKING_CHECKIN_SUCCEED";
export const BOOKING_CHECKIN_FAIL = "BOOKING_CHECKIN_FAIL";

export const BOOKING_CHECKOUT = "BOOKING_CHECKOUT";
export const BOOKING_CHECKOUT_SUCCEED = "BOOKING_CHECKOUT_SUCCEED";
export const BOOKING_CHECKOUT_FAIL = "BOOKING_CHECKOUT_FAIL";
