export const GET_SERVICE = "GET_SERVICE";
export const GET_SERVICE_SUCCEED = "GET_SERVICE_SUCCEED";
export const GET_SERVICE_FAIL = "GET_SERVICE_FAIL";

export const CREATE_SERVICE = "CREATE_SERVICE";
export const CREATE_SERVICE_SUCCEED = "CREATE_SERVICE_SUCCEED";
export const CREATE_SERVICE_FAIL = "CREATE_SERVICE_FAIL";

export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const UPDATE_SERVICE_SUCCEED = "UPDATE_SERVICE_SUCCEED";
export const UPDATE_SERVICE_FAIL = "UPDATE_SERVICE_FAIL";

export const ORDER_SERVICE = "ORDER_SERVICE";
export const ORDER_SERVICE_SUCCEED = "ORDER_SERVICE_SUCCEED";
export const ORDER_SERVICE_FAIL = "ORDER_SERVICE_FAIL";

export const INACTIVE_SERVICE = "INACTIVE_SERVICE";
export const INACTIVE_SERVICE_SUCCEED = "INACTIVE_SERVICE_SUCCEED";
export const INACTIVE_SERVICE_FAIL = "INACTIVE_SERVICE_FAIl";

export const ACTIVE_SERVICE = "ACTIVE_SERVICE";
export const ACTIVE_SERVICE_SUCCEED = "ACTIVE_SERVICE_SUCCEED";
export const ACTIVE_SERVICE_FAIL = "ACTIVE_SERVICE_FAIl";
