export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_EMPLOYEE_SUCCEED = "GET_EMPLOYEE_SUCCEED";
export const GET_EMPLOYEE_FAIL = "GET_EMPLOYEE_FAIL";

export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCEED = "UPDATE_EMPLOYEE_SUCCEED";
export const UPDATE_EMPLOYEE_FAIL = "UPDATE_EMPLOYEE_FAIL";

export const TOGGLE_EMPLOYEE = "TOGGLE_EMPLOYEE";
export const TOGGLE_EMPLOYEE_SUCCEED = "TOGGLE_EMPLOYEE";
export const TOGGLE_EMPLOYEE_FAIL = "TOGGLE_EMPLOYEE_FAIL";
