export const GET_MONTHLY_STATISTICS = "GET_MONTHLY_STATISTICS";
export const GET_MONTHLY_STATISTICS_SUCCEED = "GET_MONTHLY_STATISTICS_SUCCEED";
export const GET_MONTHLY_STATISTICS_FAIL = "GET_MONTHLY_STATISTICS_FAIL";

export const GET_ROOMS_STATISTIC = "GET_ROOMS_STATISTIC";
export const GET_ROOMS_STATISTIC_SUCCEED = "GET_ROOMS_STATISTIC_SUCCEED";
export const GET_ROOMS_STATISTIC_FAIL = "GET_ROOMS_STATISTIC_FAIL";

export const GET_SERVICE_STATISTIC = "GET_SERVICE_STATISTIC";
export const GET_SERVICE_STATISTIC_SUCCEED = "GET_SERVICE_STATISTIC_SUCCEED";
export const GET_SERVICE_STATISTIC_FAIL = "GET_SERVICE_STATISTIC_FAIL";


